### ISSUE TITLE
Add fhevm smart contracts ci workflows

### ISSUE THREAD

**Issue by tawadaa** [zama-ai/fhevm-solidity#593]
```[tasklist]
### Tasks
- [ ] https://github.com/zama-ai/fhevm/pull/595
- [ ] https://github.com/zama-ai/fhevm/pull/597
- [ ] https://github.com/zama-ai/fhevm/pull/598
```
